### ISSUE TITLE
4L 회고 / 2023-10-25

### ISSUE THREAD

**Issue by Felicette1963** [Felicette1963/Play_Data_Python_TIL#41]
# 좋았던 것(Liked)
- 없음
# 배운 것(Learned)
1. docker compose

- 여러개의 도커들을 문어 처럼 하나로 연결하여 사용하는 방식
> 준비사항
> https://github.com/Felicette1963/Play_Data_Python_TIL/issues/40
> 5. docker hub에 등록 될 것

① 도커 가져오기
```
$ docker pull felicette1963/felicette1963.github.io

Using default tag: latest
latest: Pulling from felicette1963/felicette1963.github.io
a378f10b3218: Already exists
c20157372e94: Already exists
073cbcfef663: Already exists
5f75f8a17f40: Already exists
39fc6f0c5be2: Already exists
2365018b796a: Pull complete
Digest: sha256:19c50b76bd1e5a466d9ad96daf572dac77c8e29af74c1579f97a72bb0b3e44ae
Status: Downloaded newer image for felicette1963/felicette1963.github.io:latest
docker.io/felicette1963/felicette1963.github.io:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview felicette1963/felicette1963.github.io
```

② compose.yml 파일 작성
```
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  felicette1963:
    image: felicette1963/felicette1963.github.io
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=Felicette.com
      - VIRTUAL_PORT=80
```

③ hosts 파일에 등록
위치 [C:\Windows\System32\drivers\etc\hosts]
```
# doker by Felicette1963
127.0.0.1 Felicette.com

# docker by doxgxxn
127.0.0.1 doxgxxn.com

# docker by sam1000won
127.0.0.1 sam1000won.com

# docker by tjkpolisher
127.0.0.1 tjkpolisher.com

# docker by 8trider
127.0.0.1 8trider.com
```

④ 접속하기
![image](https://github.com/Felicette1963/Play_Data_Python_TIL/assets/135789538/9c109fe9-8e76-48d9-83db-1cf8bb6a16b9)

# 부족했던 것(Lacked)
- 없음
# 바라는 것(Longed for)
- 없음
